# Generated by Django 5.1.1 on 2024-12-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knjiga',
            name='authors',
        ),
        migrations.AddField(
            model_name='knjiga',
            name='autor',
            field=models.ManyToManyField(to='main.autor'),
        ),
        migrations.AddField(
            model_name='knjiga',
            name='izdavac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.izdavac'),
        ),
    ]
